version: '2'
services:
  kong:
    image: kong
    restart: always
    environment:
      - KONG_DATABASE=cassandra
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "7946:7946"
      - "7946:7946/udp"
    depends_on:
      - kong-database
  kong-database:
    restart: always
    image: cassandra:2.2
  kong-dashboard:
    restart: always
    image: pgbi/kong-dashboard
    ports:
      - "8080:8080"
    depends_on:
      - kong
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - RRHH_API_SERVER_PORT=3000
      - RRHH_API_SERVER_HOST=0.0.0.0
      - RRHH_API_LOGGER_INFO_PATH='./info.log'
      - RRHH_API_LOGGER_INFO_LEVEL='info'
      - RRHH_API_LOGGER_FILE_MAX_SIZE=1000000
      - RRHH_API_LOGGER_MAX_FILES=50
      - RRHH_API_LOGGER_ERROR_PATH='./error.log'
      - RRHH_API_LOGGER_ERROR_LEVEL='error'
      - RRHH_API_IS_BEHIND_PROXY=false 
      - RRHH_API_MONGODB_HOST=mongo
      - RRHH_API_MONGODB_PORT=27017
      - RRHH_API_MONGODB_DB=default 
      - NODE_ENV=develop
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
