swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
  description: Hello World Application
# during dev, should point to your local machine
host: localhost:3000
# basePath prefixes all resource paths
basePath: /api
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
tags:
  - name: HelloWorld
    description: Hello World Resource
paths:
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello-world
    get:
      tags:
        - HelloWorld
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GenericResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/GenericErrorResponse"
  /fullreceipt:
    # binds a127 app logic to a route
    x-swagger-router-controller: allreceipts
    get:
      tags:
        - FullReceipt
      # used as the method name of the controller
      operationId: getAllReceipt
      parameters:
        - name: legajo
          in: query
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GenericResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/GenericErrorResponse"
  /status/{receiptID}:
    # binds a127 app logic to a route
    x-swagger-router-controller: status
    post:
      tags:
        - StatusOK
      # used as the method name of the controller
      operationId: getStatus
      parameters:
        - name: receiptID
          in: path
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GenericResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/GenericErrorResponse"
# complex objects have schema definitions
definitions:
  GenericResponse:
    required:
      - message
    properties:
      message:
        type: string
  GenericErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
